// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Canva.OpenApiClient.Models;
using Soenneker.Canva.OpenApiClient.V1.Designs.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Canva.OpenApiClient.V1.Designs
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\designs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DesignsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Canva.OpenApiClient.v1.designs.item collection</summary>
        /// <param name="position">The design ID.</param>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.V1.Designs.Item.WithDesignItemRequestBuilder"/></returns>
        public global::Soenneker.Canva.OpenApiClient.V1.Designs.Item.WithDesignItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("designId", position);
                return new global::Soenneker.Canva.OpenApiClient.V1.Designs.Item.WithDesignItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.V1.Designs.DesignsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DesignsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/designs{?continuation*,limit*,ownership*,query*,sort_by*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.V1.Designs.DesignsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DesignsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/designs{?continuation*,limit*,ownership*,query*,sort_by*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists metadata for all the designs in a Canva user&apos;s[projects](https://www.canva.com/help/find-designs-and-folders/). You can also:- Use search terms to filter the listed designs.- Show designs either created by, or shared with the user.- Sort the results.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.GetListDesignResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Canva.OpenApiClient.Models.GetListDesignResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Canva.OpenApiClient.V1.Designs.DesignsRequestBuilder.DesignsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Canva.OpenApiClient.Models.GetListDesignResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Canva.OpenApiClient.V1.Designs.DesignsRequestBuilder.DesignsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Canva.OpenApiClient.Models.GetListDesignResponse>(requestInfo, global::Soenneker.Canva.OpenApiClient.Models.GetListDesignResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new Canva design. To create a new design, you can:- Use a preset design type.- Set height and width dimensions for a custom design.  NOTE: Custom designs can have a maximum area of 25,000,000 pixels squared (for example, 5000 × 5000 pixels). Each dimension can be between 40 and 8000 pixels, but the total area must stay within this limit.- Create a copy of an existing design (currently a [preview feature](https://www.canva.dev/docs/connect/#preview-apis)).- Create a new design from a brand template (currently a [preview feature](https://www.canva.dev/docs/connect/#preview-apis)).For preset and custom designs, you can also provide the `asset_id` of an asset in the user&apos;s [projects](https://www.canva.com/help/find-designs-and-folders/) to add to the new design. Currently, this only supports image assets. To list the assets in a folder in the user&apos;s projects, use the [List folder items API](https://www.canva.dev/docs/connect/api-reference/folders/list-folder-items/).NOTE: Blank designs created with this API are automatically deleted if they&apos;re not edited within 7 days. These blank designs bypass the user&apos;s Canva trash and are permanently deleted.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreateDesignResponse"/></returns>
        /// <param name="body">Body parameters for creating a new design. Use the `type` discriminator to choose the creation mode:- Use `type_and_asset` to create a design by specifying the design type and/or an asset.- Use `design` to create a copy of an existing design (currently a [preview feature](https://www.canva.dev/docs/connect/#preview-apis)).- Use `brand_template` to create a design from a brand template (currently a [preview feature](https://www.canva.dev/docs/connect/#preview-apis)).NOTE: For backward compatibility, if `type` isn&apos;t specified in the request,the request type will be assumed to be `type_and_asset`.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Canva.OpenApiClient.Models.CreateDesignResponse?> PostAsync(global::Soenneker.Canva.OpenApiClient.Models.CreateDesignRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Canva.OpenApiClient.Models.CreateDesignResponse> PostAsync(global::Soenneker.Canva.OpenApiClient.Models.CreateDesignRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Canva.OpenApiClient.Models.CreateDesignResponse>(requestInfo, global::Soenneker.Canva.OpenApiClient.Models.CreateDesignResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists metadata for all the designs in a Canva user&apos;s[projects](https://www.canva.com/help/find-designs-and-folders/). You can also:- Use search terms to filter the listed designs.- Show designs either created by, or shared with the user.- Sort the results.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Canva.OpenApiClient.V1.Designs.DesignsRequestBuilder.DesignsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Canva.OpenApiClient.V1.Designs.DesignsRequestBuilder.DesignsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new Canva design. To create a new design, you can:- Use a preset design type.- Set height and width dimensions for a custom design.  NOTE: Custom designs can have a maximum area of 25,000,000 pixels squared (for example, 5000 × 5000 pixels). Each dimension can be between 40 and 8000 pixels, but the total area must stay within this limit.- Create a copy of an existing design (currently a [preview feature](https://www.canva.dev/docs/connect/#preview-apis)).- Create a new design from a brand template (currently a [preview feature](https://www.canva.dev/docs/connect/#preview-apis)).For preset and custom designs, you can also provide the `asset_id` of an asset in the user&apos;s [projects](https://www.canva.com/help/find-designs-and-folders/) to add to the new design. Currently, this only supports image assets. To list the assets in a folder in the user&apos;s projects, use the [List folder items API](https://www.canva.dev/docs/connect/api-reference/folders/list-folder-items/).NOTE: Blank designs created with this API are automatically deleted if they&apos;re not edited within 7 days. These blank designs bypass the user&apos;s Canva trash and are permanently deleted.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Body parameters for creating a new design. Use the `type` discriminator to choose the creation mode:- Use `type_and_asset` to create a design by specifying the design type and/or an asset.- Use `design` to create a copy of an existing design (currently a [preview feature](https://www.canva.dev/docs/connect/#preview-apis)).- Use `brand_template` to create a design from a brand template (currently a [preview feature](https://www.canva.dev/docs/connect/#preview-apis)).NOTE: For backward compatibility, if `type` isn&apos;t specified in the request,the request type will be assumed to be `type_and_asset`.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Canva.OpenApiClient.Models.CreateDesignRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Canva.OpenApiClient.Models.CreateDesignRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.V1.Designs.DesignsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Canva.OpenApiClient.V1.Designs.DesignsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Canva.OpenApiClient.V1.Designs.DesignsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists metadata for all the designs in a Canva user&apos;s[projects](https://www.canva.com/help/find-designs-and-folders/). You can also:- Use search terms to filter the listed designs.- Show designs either created by, or shared with the user.- Sort the results.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DesignsRequestBuilderGetQueryParameters 
        {
            /// <summary>If the success response contains a continuation token, the list contains more designsyou can list. You can use this token as a query parameter and retrieve moredesigns from the list, for example`/v1/designs?continuation={continuation}`.To retrieve all of a user&apos;s designs, you might need to make multiple requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("continuation")]
            public string? Continuation { get; set; }
#nullable restore
#else
            [QueryParameter("continuation")]
            public string Continuation { get; set; }
#endif
            /// <summary>The number of designs to return.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Filter the list of designs based on the user&apos;s ownership of the designs.</summary>
            [QueryParameter("ownership")]
            public global::Soenneker.Canva.OpenApiClient.Models.OwnershipType? Ownership { get; set; }
            /// <summary>Lets you search the user&apos;s designs, and designs shared with the user, using a search term or terms.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>Sort the list of designs.</summary>
            [QueryParameter("sort_by")]
            public global::Soenneker.Canva.OpenApiClient.Models.SortByType? SortBy { get; set; }
        }
    }
}
#pragma warning restore CS0618
