// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Canva.OpenApiClient.V1.Apps.Item.Jwks;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Canva.OpenApiClient.V1.Apps.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\apps\{appId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithAppItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The jwks property</summary>
        public global::Soenneker.Canva.OpenApiClient.V1.Apps.Item.Jwks.JwksRequestBuilder Jwks
        {
            get => new global::Soenneker.Canva.OpenApiClient.V1.Apps.Item.Jwks.JwksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.V1.Apps.Item.WithAppItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAppItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/apps/{appId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.V1.Apps.Item.WithAppItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAppItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/apps/{appId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
