// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Canva.OpenApiClient.Models;
using Soenneker.Canva.OpenApiClient.V1.Generations.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Canva.OpenApiClient.V1.Generations
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\generations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GenerationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Canva.OpenApiClient.v1.generations.item collection</summary>
        /// <param name="position">The public design generation job ID.</param>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.V1.Generations.Item.WithJobItemRequestBuilder"/></returns>
        public global::Soenneker.Canva.OpenApiClient.V1.Generations.Item.WithJobItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("jobId", position);
                return new global::Soenneker.Canva.OpenApiClient.V1.Generations.Item.WithJobItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.V1.Generations.GenerationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GenerationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/generations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.V1.Generations.GenerationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GenerationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/generations", rawUrl)
        {
        }
        /// <summary>
        /// &lt;Warning&gt;This API is currently provided as a preview. Be aware of the following:- There might be unannounced breaking changes.- Any breaking changes to preview APIs won&apos;t produce a new [API version](https://www.canva.dev/docs/apps/rest-apis/versions/).- Public integrations that use preview APIs will not pass the review process, and can&apos;t be made available to all Canva users.&lt;/Warning&gt;Starts a new [asynchronous job](https://www.canva.dev/docs/apps/rest-apis/requests-responses/#asynchronous-job-endpoints) to generate a Canva design from a text brief. A successful job includes metadata for the generated design, which is saved to the user&apos;s Canva account.You can generate a document or presentation. For presentations, you can also provide an outline of the slides to generate.Requires the `design_generation` capability. You can check whether the user has this capability using the [Get user capabilities API](https://www.canva.dev/docs/apps/rest-apis/reference/users/get-user-capabilities/).Starting a job consumes the user&apos;s [AI credit allowance](https://www.canva.com/help/ai-access/). If the user has reached their AI allowance limit, the request returns a `429` error with the `credit_quota_exceeded` code. Polling for the result of a job doesn&apos;t consume any of the allowance.&lt;Note&gt;For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/apps/rest-apis/requests-responses/#asynchronous-job-endpoints). You can check the status and get the results of jobs created with this API using the [Get design generation job API](https://www.canva.dev/docs/apps/rest-apis/reference/generations/get-design-generation-job/).&lt;/Note&gt;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreateDesignGenerationJobResponseV2"/></returns>
        /// <param name="body">The brief, design type, and optional presentation outline for generation.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.CreditQuotaError">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Canva.OpenApiClient.Models.CreateDesignGenerationJobResponseV2?> PostAsync(global::Soenneker.Canva.OpenApiClient.Models.CreateDesignGenerationJobRequestV2 body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Canva.OpenApiClient.Models.CreateDesignGenerationJobResponseV2> PostAsync(global::Soenneker.Canva.OpenApiClient.Models.CreateDesignGenerationJobRequestV2 body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Canva.OpenApiClient.Models.CreditQuotaError.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Canva.OpenApiClient.Models.CreateDesignGenerationJobResponseV2>(requestInfo, global::Soenneker.Canva.OpenApiClient.Models.CreateDesignGenerationJobResponseV2.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;Warning&gt;This API is currently provided as a preview. Be aware of the following:- There might be unannounced breaking changes.- Any breaking changes to preview APIs won&apos;t produce a new [API version](https://www.canva.dev/docs/apps/rest-apis/versions/).- Public integrations that use preview APIs will not pass the review process, and can&apos;t be made available to all Canva users.&lt;/Warning&gt;Starts a new [asynchronous job](https://www.canva.dev/docs/apps/rest-apis/requests-responses/#asynchronous-job-endpoints) to generate a Canva design from a text brief. A successful job includes metadata for the generated design, which is saved to the user&apos;s Canva account.You can generate a document or presentation. For presentations, you can also provide an outline of the slides to generate.Requires the `design_generation` capability. You can check whether the user has this capability using the [Get user capabilities API](https://www.canva.dev/docs/apps/rest-apis/reference/users/get-user-capabilities/).Starting a job consumes the user&apos;s [AI credit allowance](https://www.canva.com/help/ai-access/). If the user has reached their AI allowance limit, the request returns a `429` error with the `credit_quota_exceeded` code. Polling for the result of a job doesn&apos;t consume any of the allowance.&lt;Note&gt;For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/apps/rest-apis/requests-responses/#asynchronous-job-endpoints). You can check the status and get the results of jobs created with this API using the [Get design generation job API](https://www.canva.dev/docs/apps/rest-apis/reference/generations/get-design-generation-job/).&lt;/Note&gt;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The brief, design type, and optional presentation outline for generation.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Canva.OpenApiClient.Models.CreateDesignGenerationJobRequestV2 body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Canva.OpenApiClient.Models.CreateDesignGenerationJobRequestV2 body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.V1.Generations.GenerationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Canva.OpenApiClient.V1.Generations.GenerationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Canva.OpenApiClient.V1.Generations.GenerationsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
