// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AddType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "add")]
        #pragma warning disable CS1591
        Add,
        #pragma warning restore CS1591
    }
}
