// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// The status of the asset upload job.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AssetUploadJob : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The asset object, which contains metadata about the asset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.Asset? Asset { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.Asset Asset { get; set; }
#endif
        /// <summary>If the upload fails, this object provides details about the error.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.AssetUploadError? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.AssetUploadError Error { get; set; }
#endif
        /// <summary>The ID of the asset upload job.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Status of the asset upload job.</summary>
        public global::Soenneker.Canva.OpenApiClient.Models.AssetUploadStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.AssetUploadJob"/> and sets the default values.
        /// </summary>
        public AssetUploadJob()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.AssetUploadJob"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.AssetUploadJob CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.AssetUploadJob();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "asset", n => { Asset = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.Asset>(global::Soenneker.Canva.OpenApiClient.Models.Asset.CreateFromDiscriminatorValue); } },
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.AssetUploadError>(global::Soenneker.Canva.OpenApiClient.Models.AssetUploadError.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Canva.OpenApiClient.Models.AssetUploadStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.Asset>("asset", Asset);
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.AssetUploadError>("error", Error);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Canva.OpenApiClient.Models.AssetUploadStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
