// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ByLinkType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "by_link")]
        #pragma warning disable CS1591
        ByLink,
        #pragma warning restore CS1591
    }
}
