// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>Some APIs are annotated with required capabilities. These endpoints require the user topossess the required capabilities in order to be called successfully.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Capability
    {
        [EnumMember(Value = "analytics")]
        #pragma warning disable CS1591
        Analytics,
        #pragma warning restore CS1591
        [EnumMember(Value = "autofill")]
        #pragma warning disable CS1591
        Autofill,
        #pragma warning restore CS1591
        [EnumMember(Value = "brand_template")]
        #pragma warning disable CS1591
        BrandTemplate,
        #pragma warning restore CS1591
        [EnumMember(Value = "export_png_transparency")]
        #pragma warning disable CS1591
        ExportPngTransparency,
        #pragma warning restore CS1591
        [EnumMember(Value = "resize")]
        #pragma warning disable CS1591
        Resize,
        #pragma warning restore CS1591
        [EnumMember(Value = "team_restricted_app")]
        #pragma warning disable CS1591
        TeamRestrictedApp,
        #pragma warning restore CS1591
    }
}
