// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateFromDesignType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "create_from_design")]
        #pragma warning disable CS1591
        CreateFromDesign,
        #pragma warning restore CS1591
    }
}
