// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Canva.OpenApiClient.Models.BrandTemplateCreateDesignRequest"/>, <see cref="global::Soenneker.Canva.OpenApiClient.Models.DesignCreateDesignRequest"/>, <see cref="global::Soenneker.Canva.OpenApiClient.Models.DesignTypeCreateDesignRequest"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateDesignRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.BrandTemplateCreateDesignRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.BrandTemplateCreateDesignRequest? BrandTemplateCreateDesignRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.BrandTemplateCreateDesignRequest BrandTemplateCreateDesignRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.DesignCreateDesignRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.DesignCreateDesignRequest? DesignCreateDesignRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.DesignCreateDesignRequest DesignCreateDesignRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.DesignTypeCreateDesignRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.DesignTypeCreateDesignRequest? DesignTypeCreateDesignRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.DesignTypeCreateDesignRequest DesignTypeCreateDesignRequest { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreateDesignRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.CreateDesignRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Canva.OpenApiClient.Models.CreateDesignRequest();
            if("BrandTemplateCreateDesignRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BrandTemplateCreateDesignRequest = new global::Soenneker.Canva.OpenApiClient.Models.BrandTemplateCreateDesignRequest();
            }
            else if("design".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DesignCreateDesignRequest = new global::Soenneker.Canva.OpenApiClient.Models.DesignCreateDesignRequest();
            }
            else if("DesignTypeCreateDesignRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DesignTypeCreateDesignRequest = new global::Soenneker.Canva.OpenApiClient.Models.DesignTypeCreateDesignRequest();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(BrandTemplateCreateDesignRequest != null)
            {
                return BrandTemplateCreateDesignRequest.GetFieldDeserializers();
            }
            else if(DesignCreateDesignRequest != null)
            {
                return DesignCreateDesignRequest.GetFieldDeserializers();
            }
            else if(DesignTypeCreateDesignRequest != null)
            {
                return DesignTypeCreateDesignRequest.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(BrandTemplateCreateDesignRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.BrandTemplateCreateDesignRequest>(null, BrandTemplateCreateDesignRequest);
            }
            else if(DesignCreateDesignRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.DesignCreateDesignRequest>(null, DesignCreateDesignRequest);
            }
            else if(DesignTypeCreateDesignRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.DesignTypeCreateDesignRequest>(null, DesignTypeCreateDesignRequest);
            }
        }
    }
}
#pragma warning restore CS0618
