// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>For backward compatibility, if `type` isn&apos;t specified in the request, the request type is assumed to be `create_from_brand_template`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateFromBrandTemplateType
    {
        [EnumMember(Value = "create_from_brand_template")]
        #pragma warning disable CS1591
        CreateFromBrandTemplate,
        #pragma warning restore CS1591
    }
}
