// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequest"/>, <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreateFromDesignAutofillJobRequest"/>, <see cref="global::Soenneker.Canva.OpenApiClient.Models.UpdateDesignAutofillJobRequest"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateDesignAutofillJobRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequest? CreateFromBrandTemplateAutofillJobRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequest CreateFromBrandTemplateAutofillJobRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreateFromDesignAutofillJobRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.CreateFromDesignAutofillJobRequest? CreateFromDesignAutofillJobRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.CreateFromDesignAutofillJobRequest CreateFromDesignAutofillJobRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.UpdateDesignAutofillJobRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.UpdateDesignAutofillJobRequest? UpdateDesignAutofillJobRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.UpdateDesignAutofillJobRequest UpdateDesignAutofillJobRequest { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreateDesignAutofillJobRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.CreateDesignAutofillJobRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Canva.OpenApiClient.Models.CreateDesignAutofillJobRequest();
            if("CreateFromBrandTemplateAutofillJobRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CreateFromBrandTemplateAutofillJobRequest = new global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequest();
            }
            else if("CreateFromDesignAutofillJobRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CreateFromDesignAutofillJobRequest = new global::Soenneker.Canva.OpenApiClient.Models.CreateFromDesignAutofillJobRequest();
            }
            else if("UpdateDesignAutofillJobRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateDesignAutofillJobRequest = new global::Soenneker.Canva.OpenApiClient.Models.UpdateDesignAutofillJobRequest();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CreateFromBrandTemplateAutofillJobRequest != null)
            {
                return CreateFromBrandTemplateAutofillJobRequest.GetFieldDeserializers();
            }
            else if(CreateFromDesignAutofillJobRequest != null)
            {
                return CreateFromDesignAutofillJobRequest.GetFieldDeserializers();
            }
            else if(UpdateDesignAutofillJobRequest != null)
            {
                return UpdateDesignAutofillJobRequest.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CreateFromBrandTemplateAutofillJobRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequest>(null, CreateFromBrandTemplateAutofillJobRequest);
            }
            else if(CreateFromDesignAutofillJobRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.CreateFromDesignAutofillJobRequest>(null, CreateFromDesignAutofillJobRequest);
            }
            else if(UpdateDesignAutofillJobRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.UpdateDesignAutofillJobRequest>(null, UpdateDesignAutofillJobRequest);
            }
        }
    }
}
#pragma warning restore CS0618
