// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Body parameters for starting a Print Partner export job for a design.It must include a design ID. Canva Docs are not supported for export.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreatePrintPartnerDesignExportJobRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The design ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DesignId { get; set; }
#nullable restore
#else
        public string DesignId { get; set; }
#endif
        /// <summary>Dimensions of the export in the specified units. The design dimensions must bewithin a scale factor of 0.3 and 3 of the requested export dimensions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerExportDimensions? Dimensions { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerExportDimensions Dimensions { get; set; }
#endif
        /// <summary>Details about the desired export format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerExportFormat? Format { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerExportFormat Format { get; set; }
#endif
        /// <summary>To specify which pages to export in a multi-page design, provide the pagenumbers as an array. The first page in a design is page `1`.If `pages` isn&apos;t specified, all the pages are exported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Pages { get; set; }
#nullable restore
#else
        public List<int?> Pages { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreatePrintPartnerDesignExportJobRequest"/> and sets the default values.
        /// </summary>
        public CreatePrintPartnerDesignExportJobRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreatePrintPartnerDesignExportJobRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.CreatePrintPartnerDesignExportJobRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.CreatePrintPartnerDesignExportJobRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "design_id", n => { DesignId = n.GetStringValue(); } },
                { "dimensions", n => { Dimensions = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerExportDimensions>(global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerExportDimensions.CreateFromDiscriminatorValue); } },
                { "format", n => { Format = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerExportFormat>(global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerExportFormat.CreateFromDiscriminatorValue); } },
                { "pages", n => { Pages = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("design_id", DesignId);
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerExportDimensions>("dimensions", Dimensions);
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerExportFormat>("format", Format);
            writer.WriteCollectionOfPrimitiveValues<int?>("pages", Pages);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
