// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateDesignType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "create_design")]
        #pragma warning disable CS1591
        CreateDesign,
        #pragma warning restore CS1591
    }
}
