// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Body parameters for creating a new design for a Print Partner.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreatePrintPartnerDesignRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Bleed in microns to apply around the design in the editor. Bleed is the areaoutside the trim line used to avoid white edges after cutting. Use 0 for no bleed. If bleed is notspecified, a default of 3000 microns is used.</summary>
        public int? Bleed { get; set; }
        /// <summary>The desired source for the design creation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerDesignSource? DesignSource { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerDesignSource DesignSource { get; set; }
#endif
        /// <summary>Maximum number of pages the design can have in the editor. The user cannotadd pages beyond this value. If both min_pages and max_pages are provided,min_pages must be less than or equal to max_pages.</summary>
        public int? MaxPages { get; set; }
        /// <summary>Minimum number of pages the design must have in the editor. The user cannotreduce the page count below this value. If both min_pages and max_pages areprovided, min_pages must be less than or equal to max_pages.</summary>
        public int? MinPages { get; set; }
        /// <summary>The name of the design.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreatePrintPartnerDesignRequest"/> and sets the default values.
        /// </summary>
        public CreatePrintPartnerDesignRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            Bleed = 3000;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreatePrintPartnerDesignRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.CreatePrintPartnerDesignRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.CreatePrintPartnerDesignRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bleed", n => { Bleed = n.GetIntValue(); } },
                { "design_source", n => { DesignSource = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerDesignSource>(global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerDesignSource.CreateFromDiscriminatorValue); } },
                { "max_pages", n => { MaxPages = n.GetIntValue(); } },
                { "min_pages", n => { MinPages = n.GetIntValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("bleed", Bleed);
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.PrintPartnerDesignSource>("design_source", DesignSource);
            writer.WriteIntValue("max_pages", MaxPages);
            writer.WriteIntValue("min_pages", MinPages);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
