// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Create a new autofilled design from a brand template.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateFromBrandTemplateAutofillJobRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ID of the input brand template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BrandTemplateId { get; set; }
#nullable restore
#else
        public string BrandTemplateId { get; set; }
#endif
        /// <summary>Data object containing the data fields and values to autofill.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequestDataProperty? Data { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequestDataProperty Data { get; set; }
#endif
        /// <summary>Title to use for the autofilled design.If no design title is provided, the autofilled design will have the same title as the brand template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>For backward compatibility, if `type` isn&apos;t specified in the request, the request type is assumed to be `create_from_brand_template`.</summary>
        public global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequest"/> and sets the default values.
        /// </summary>
        public CreateFromBrandTemplateAutofillJobRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "brand_template_id", n => { BrandTemplateId = n.GetStringValue(); } },
                { "data", n => { Data = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequestDataProperty>(global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequestDataProperty.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("brand_template_id", BrandTemplateId);
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateAutofillJobRequestDataProperty>("data", Data);
            writer.WriteStringValue("title", Title);
            writer.WriteEnumValue<global::Soenneker.Canva.OpenApiClient.Models.CreateFromBrandTemplateType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
