// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>The type of merge operation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeletePagesType
    {
        [EnumMember(Value = "delete_pages")]
        #pragma warning disable CS1591
        DeletePages,
        #pragma warning restore CS1591
    }
}
