// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>How this viewer should be presented to the caller.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DesignAnalyticsViewerVisibility
    {
        [EnumMember(Value = "shown")]
        #pragma warning disable CS1591
        Shown,
        #pragma warning restore CS1591
        [EnumMember(Value = "anonymous")]
        #pragma warning disable CS1591
        Anonymous,
        #pragma warning restore CS1591
        [EnumMember(Value = "opt_out")]
        #pragma warning disable CS1591
        OptOut,
        #pragma warning restore CS1591
        [EnumMember(Value = "another_team")]
        #pragma warning disable CS1591
        AnotherTeam,
        #pragma warning restore CS1591
        [EnumMember(Value = "deleted")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
    }
}
