// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>The reason the design generation job failed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DesignGenerationJobErrorCodeV2
    {
        [EnumMember(Value = "content_not_allowed")]
        #pragma warning disable CS1591
        ContentNotAllowed,
        #pragma warning restore CS1591
        [EnumMember(Value = "generation_failed")]
        #pragma warning disable CS1591
        GenerationFailed,
        #pragma warning restore CS1591
    }
}
