// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DesignMergeErrorCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "thumbnail_generation_error")]
        #pragma warning disable CS1591
        ThumbnailGenerationError,
        #pragma warning restore CS1591
        [EnumMember(Value = "merge_error")]
        #pragma warning disable CS1591
        MergeError,
        #pragma warning restore CS1591
        [EnumMember(Value = "create_design_error")]
        #pragma warning disable CS1591
        CreateDesignError,
        #pragma warning restore CS1591
        [EnumMember(Value = "modify_design_error")]
        #pragma warning disable CS1591
        ModifyDesignError,
        #pragma warning restore CS1591
    }
}
