// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>The kind of design type to generate.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DesignGenerationDesignTypeV2
    {
        [EnumMember(Value = "preset")]
        #pragma warning disable CS1591
        Preset,
        #pragma warning restore CS1591
    }
}
