// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>How the viewer accessed the design.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DesignAnalyticsViewerType
    {
        [EnumMember(Value = "editor")]
        #pragma warning disable CS1591
        Editor,
        #pragma warning restore CS1591
        [EnumMember(Value = "commenter")]
        #pragma warning disable CS1591
        Commenter,
        #pragma warning restore CS1591
        [EnumMember(Value = "viewer")]
        #pragma warning disable CS1591
        Viewer,
        #pragma warning restore CS1591
    }
}
