// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>A short string about why the import failed. This field can be used to handle errorsprogrammatically.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DesignImportErrorCode
    {
        [EnumMember(Value = "design_creation_throttled")]
        #pragma warning disable CS1591
        DesignCreationThrottled,
        #pragma warning restore CS1591
        [EnumMember(Value = "design_import_throttled")]
        #pragma warning disable CS1591
        DesignImportThrottled,
        #pragma warning restore CS1591
        [EnumMember(Value = "duplicate_import")]
        #pragma warning disable CS1591
        DuplicateImport,
        #pragma warning restore CS1591
        [EnumMember(Value = "internal_error")]
        #pragma warning disable CS1591
        InternalError,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_file")]
        #pragma warning disable CS1591
        InvalidFile,
        #pragma warning restore CS1591
        [EnumMember(Value = "fetch_failed")]
        #pragma warning disable CS1591
        FetchFailed,
        #pragma warning restore CS1591
    }
}
