// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Canva.OpenApiClient.Models.CustomDesignTypeInput"/>, <see cref="global::Soenneker.Canva.OpenApiClient.Models.PresetDesignTypeInput"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DesignTypeInput : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.CustomDesignTypeInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.CustomDesignTypeInput? CustomDesignTypeInput { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.CustomDesignTypeInput CustomDesignTypeInput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.PresetDesignTypeInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.PresetDesignTypeInput? PresetDesignTypeInput { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.PresetDesignTypeInput PresetDesignTypeInput { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.DesignTypeInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.DesignTypeInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Canva.OpenApiClient.Models.DesignTypeInput();
            if("custom".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CustomDesignTypeInput = new global::Soenneker.Canva.OpenApiClient.Models.CustomDesignTypeInput();
            }
            else if("preset".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PresetDesignTypeInput = new global::Soenneker.Canva.OpenApiClient.Models.PresetDesignTypeInput();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CustomDesignTypeInput != null)
            {
                return CustomDesignTypeInput.GetFieldDeserializers();
            }
            else if(PresetDesignTypeInput != null)
            {
                return PresetDesignTypeInput.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CustomDesignTypeInput != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.CustomDesignTypeInput>(null, CustomDesignTypeInput);
            }
            else if(PresetDesignTypeInput != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.PresetDesignTypeInput>(null, PresetDesignTypeInput);
            }
        }
    }
}
#pragma warning restore CS0618
