// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// The status and result of a public design generation job.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DesignGenerationJobV2 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Details about a failed design generation job.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobErrorV2? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobErrorV2 Error { get; set; }
#endif
        /// <summary>The public design generation job ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Present only when the job status is `success`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobResultV2? Result { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobResultV2 Result { get; set; }
#endif
        /// <summary>The public status of the job. `result` is present only for `success`, and`error` is present only for `failed`.</summary>
        public global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobStatusV2? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobV2"/> and sets the default values.
        /// </summary>
        public DesignGenerationJobV2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobV2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobV2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobV2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobErrorV2>(global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobErrorV2.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "result", n => { Result = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobResultV2>(global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobResultV2.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobStatusV2>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobErrorV2>("error", Error);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobResultV2>("result", Result);
            writer.WriteEnumValue<global::Soenneker.Canva.OpenApiClient.Models.DesignGenerationJobStatusV2>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
