// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Basic details about a page in a design, such as the page number and thumbnail.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DesignPage : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The type of content a design or page contains. The list of design types may grow over time. The `unknown` value represents design types that haven&apos;t been added to the list.</summary>
        public global::Soenneker.Canva.OpenApiClient.Models.DesignTypeOutputName? DesignType { get; set; }
        /// <summary>The dimensions of a design page, if it is bounded. Design pages for non-bounded designs like Whiteboards and Docs will not include this property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.PageDimensions? Dimensions { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.PageDimensions Dimensions { get; set; }
#endif
        /// <summary>The ID of the page. This ID is unique within the design and can be used tocorrelate a page with per-page data from other APIs.Some designs might not have page IDs, in which case this property is omitted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>WARNING: This property is deprecated. Use `page_number` instead, which returns an identical value.The index of the page in the design. The first page in a design has the index value `1`.</summary>
        [Obsolete("")]
        public int? Index { get; set; }
        /// <summary>The 1-based page number within the design. The first page in a design has the value `1`.</summary>
        public int? PageNumber { get; set; }
        /// <summary>A thumbnail image representing the object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.Thumbnail? Thumbnail { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.Thumbnail Thumbnail { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.DesignPage"/> and sets the default values.
        /// </summary>
        public DesignPage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.DesignPage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.DesignPage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.DesignPage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "design_type", n => { DesignType = n.GetEnumValue<global::Soenneker.Canva.OpenApiClient.Models.DesignTypeOutputName>(); } },
                { "dimensions", n => { Dimensions = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.PageDimensions>(global::Soenneker.Canva.OpenApiClient.Models.PageDimensions.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "index", n => { Index = n.GetIntValue(); } },
                { "page_number", n => { PageNumber = n.GetIntValue(); } },
                { "thumbnail", n => { Thumbnail = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.Thumbnail>(global::Soenneker.Canva.OpenApiClient.Models.Thumbnail.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Canva.OpenApiClient.Models.DesignTypeOutputName>("design_type", DesignType);
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.PageDimensions>("dimensions", Dimensions);
            writer.WriteStringValue("id", Id);
            writer.WriteIntValue("index", Index);
            writer.WriteIntValue("page_number", PageNumber);
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.Thumbnail>("thumbnail", Thumbnail);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
