// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Canva.OpenApiClient.Models.DeletePagesDesignMergeOperation"/>, <see cref="global::Soenneker.Canva.OpenApiClient.Models.InsertPagesDesignMergeOperation"/>, <see cref="global::Soenneker.Canva.OpenApiClient.Models.MovePagesDesignMergeOperation"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DesignMergeOperation : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.DeletePagesDesignMergeOperation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.DeletePagesDesignMergeOperation? DeletePagesDesignMergeOperation { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.DeletePagesDesignMergeOperation DeletePagesDesignMergeOperation { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.InsertPagesDesignMergeOperation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.InsertPagesDesignMergeOperation? InsertPagesDesignMergeOperation { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.InsertPagesDesignMergeOperation InsertPagesDesignMergeOperation { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.MovePagesDesignMergeOperation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.MovePagesDesignMergeOperation? MovePagesDesignMergeOperation { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.MovePagesDesignMergeOperation MovePagesDesignMergeOperation { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.DesignMergeOperation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.DesignMergeOperation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Canva.OpenApiClient.Models.DesignMergeOperation();
            if("DeletePagesDesignMergeOperation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DeletePagesDesignMergeOperation = new global::Soenneker.Canva.OpenApiClient.Models.DeletePagesDesignMergeOperation();
            }
            else if("InsertPagesDesignMergeOperation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InsertPagesDesignMergeOperation = new global::Soenneker.Canva.OpenApiClient.Models.InsertPagesDesignMergeOperation();
            }
            else if("MovePagesDesignMergeOperation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MovePagesDesignMergeOperation = new global::Soenneker.Canva.OpenApiClient.Models.MovePagesDesignMergeOperation();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(DeletePagesDesignMergeOperation != null)
            {
                return DeletePagesDesignMergeOperation.GetFieldDeserializers();
            }
            else if(InsertPagesDesignMergeOperation != null)
            {
                return InsertPagesDesignMergeOperation.GetFieldDeserializers();
            }
            else if(MovePagesDesignMergeOperation != null)
            {
                return MovePagesDesignMergeOperation.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(DeletePagesDesignMergeOperation != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.DeletePagesDesignMergeOperation>(null, DeletePagesDesignMergeOperation);
            }
            else if(InsertPagesDesignMergeOperation != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.InsertPagesDesignMergeOperation>(null, InsertPagesDesignMergeOperation);
            }
            else if(MovePagesDesignMergeOperation != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.MovePagesDesignMergeOperation>(null, MovePagesDesignMergeOperation);
            }
        }
    }
}
#pragma warning restore CS0618
