// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>The device form factor used to view the design.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DesignAnalyticsViewerFormFactor
    {
        [EnumMember(Value = "small")]
        #pragma warning disable CS1591
        Small,
        #pragma warning restore CS1591
        [EnumMember(Value = "large")]
        #pragma warning disable CS1591
        Large,
        #pragma warning restore CS1591
    }
}
