// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreateDesignAutofillJobResult"/>, <see cref="global::Soenneker.Canva.OpenApiClient.Models.UpdateDesignAutofillJobResult"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DesignAutofillJobResult : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.CreateDesignAutofillJobResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.CreateDesignAutofillJobResult? CreateDesignAutofillJobResult { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.CreateDesignAutofillJobResult CreateDesignAutofillJobResult { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.UpdateDesignAutofillJobResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.UpdateDesignAutofillJobResult? UpdateDesignAutofillJobResult { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.UpdateDesignAutofillJobResult UpdateDesignAutofillJobResult { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.DesignAutofillJobResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.DesignAutofillJobResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Canva.OpenApiClient.Models.DesignAutofillJobResult();
            if("CreateDesignAutofillJobResult".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CreateDesignAutofillJobResult = new global::Soenneker.Canva.OpenApiClient.Models.CreateDesignAutofillJobResult();
            }
            else if("UpdateDesignAutofillJobResult".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateDesignAutofillJobResult = new global::Soenneker.Canva.OpenApiClient.Models.UpdateDesignAutofillJobResult();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CreateDesignAutofillJobResult != null)
            {
                return CreateDesignAutofillJobResult.GetFieldDeserializers();
            }
            else if(UpdateDesignAutofillJobResult != null)
            {
                return UpdateDesignAutofillJobResult.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CreateDesignAutofillJobResult != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.CreateDesignAutofillJobResult>(null, CreateDesignAutofillJobResult);
            }
            else if(UpdateDesignAutofillJobResult != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.UpdateDesignAutofillJobResult>(null, UpdateDesignAutofillJobResult);
            }
        }
    }
}
#pragma warning restore CS0618
