// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// A JSON Web Key Set (JWKS) using the Edwards-curve Digital Signature Algorithm (EdDSA), asdescribed in [RFC-8037](https://www.rfc-editor.org/rfc/rfc8037.html#appendix-A).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EdDsaJwk : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The `crv` (curve) property identifies the curve used for elliptical curveencryptions. Only &quot;Ed25519&quot; is supported. For more information on the `crv`property, see [RFC-8037 — Key Type&quot;OKP&quot;](https://www.rfc-editor.org/rfc/rfc8037.html#section-2).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Crv { get; set; }
#nullable restore
#else
        public string Crv { get; set; }
#endif
        /// <summary>The `kid` (key ID) is a unique identifier for a public key. When the keys usedto sign webhooks are rotated, you can use this ID to select the correct keywithin a JWK Set during the key rollover. The `kid` value is case-sensitive.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kid { get; set; }
#nullable restore
#else
        public string Kid { get; set; }
#endif
        /// <summary>The `kty` (key type) identifies the cryptographic algorithm family used withthe key, such as &quot;RSA&quot; or &quot;EC&quot;. Only Octet Key Pairs(`OKPs`) are supported.The `kty` value is case-sensitive. For more information on the `kty` propertyand OKPs, see [RFC-8037 — &quot;kty&quot; (Key Type)Parameter](https://www.rfc-editor.org/rfc/rfc8037.html#section-2).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kty { get; set; }
#nullable restore
#else
        public string Kty { get; set; }
#endif
        /// <summary>The `x` property is the public key of an elliptical curve encryption. The keyis Base64urlUInt-encoded. For more information on the `x` property, see[RFC-8037 — &quot;x&quot; (X Coordinate)Parameter](https://www.rfc-editor.org/rfc/rfc8037#section-2).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? X { get; set; }
#nullable restore
#else
        public string X { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.EdDsaJwk"/> and sets the default values.
        /// </summary>
        public EdDsaJwk()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.EdDsaJwk"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.EdDsaJwk CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.EdDsaJwk();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "crv", n => { Crv = n.GetStringValue(); } },
                { "kid", n => { Kid = n.GetStringValue(); } },
                { "kty", n => { Kty = n.GetStringValue(); } },
                { "x", n => { X = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("crv", Crv);
            writer.WriteStringValue("kid", Kid);
            writer.WriteStringValue("kty", Kty);
            writer.WriteStringValue("x", X);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
