// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>A short string indicating what failed. This field can be used to handle errors programmatically.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ErrorCode
    {
        [EnumMember(Value = "internal_error")]
        #pragma warning disable CS1591
        InternalError,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_field")]
        #pragma warning disable CS1591
        InvalidField,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_header_value")]
        #pragma warning disable CS1591
        InvalidHeaderValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "permission_denied")]
        #pragma warning disable CS1591
        PermissionDenied,
        #pragma warning restore CS1591
        [EnumMember(Value = "too_many_requests")]
        #pragma warning disable CS1591
        TooManyRequests,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_found")]
        #pragma warning disable CS1591
        NotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "bad_request_body")]
        #pragma warning disable CS1591
        BadRequestBody,
        #pragma warning restore CS1591
        [EnumMember(Value = "bad_http_method")]
        #pragma warning disable CS1591
        BadHttpMethod,
        #pragma warning restore CS1591
        [EnumMember(Value = "bad_request_params")]
        #pragma warning disable CS1591
        BadRequestParams,
        #pragma warning restore CS1591
        [EnumMember(Value = "bad_query_params")]
        #pragma warning disable CS1591
        BadQueryParams,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_role_required")]
        #pragma warning disable CS1591
        UserRoleRequired,
        #pragma warning restore CS1591
        [EnumMember(Value = "endpoint_not_found")]
        #pragma warning disable CS1591
        EndpointNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "endpoint_gone")]
        #pragma warning disable CS1591
        EndpointGone,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsupported_version")]
        #pragma warning disable CS1591
        UnsupportedVersion,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_access_token")]
        #pragma warning disable CS1591
        InvalidAccessToken,
        #pragma warning restore CS1591
        [EnumMember(Value = "revoked_access_token")]
        #pragma warning disable CS1591
        RevokedAccessToken,
        #pragma warning restore CS1591
        [EnumMember(Value = "missing_field")]
        #pragma warning disable CS1591
        MissingField,
        #pragma warning restore CS1591
        [EnumMember(Value = "missing_scope")]
        #pragma warning disable CS1591
        MissingScope,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_grant")]
        #pragma warning disable CS1591
        InvalidGrant,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_request")]
        #pragma warning disable CS1591
        InvalidRequest,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_client")]
        #pragma warning disable CS1591
        InvalidClient,
        #pragma warning restore CS1591
        [EnumMember(Value = "unauthorized_client")]
        #pragma warning disable CS1591
        UnauthorizedClient,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsupported_grant_type")]
        #pragma warning disable CS1591
        UnsupportedGrantType,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_scope")]
        #pragma warning disable CS1591
        InvalidScope,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_basic_header")]
        #pragma warning disable CS1591
        InvalidBasicHeader,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_file_format")]
        #pragma warning disable CS1591
        InvalidFileFormat,
        #pragma warning restore CS1591
        [EnumMember(Value = "quota_exceeded")]
        #pragma warning disable CS1591
        QuotaExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "ai_credit_quota_exceeded")]
        #pragma warning disable CS1591
        AiCreditQuotaExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "ai_credit_quota_cooldown")]
        #pragma warning disable CS1591
        AiCreditQuotaCooldown,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsupported_content_type")]
        #pragma warning disable CS1591
        UnsupportedContentType,
        #pragma warning restore CS1591
        [EnumMember(Value = "request_too_large")]
        #pragma warning disable CS1591
        RequestTooLarge,
        #pragma warning restore CS1591
        [EnumMember(Value = "folder_not_found")]
        #pragma warning disable CS1591
        FolderNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "item_in_multiple_folders")]
        #pragma warning disable CS1591
        ItemInMultipleFolders,
        #pragma warning restore CS1591
        [EnumMember(Value = "asset_not_found")]
        #pragma warning disable CS1591
        AssetNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "max_limit_reached")]
        #pragma warning disable CS1591
        MaxLimitReached,
        #pragma warning restore CS1591
        [EnumMember(Value = "permission_not_found")]
        #pragma warning disable CS1591
        PermissionNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "permission_exists")]
        #pragma warning disable CS1591
        PermissionExists,
        #pragma warning restore CS1591
        [EnumMember(Value = "unauthorized_user")]
        #pragma warning disable CS1591
        UnauthorizedUser,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_not_found")]
        #pragma warning disable CS1591
        UserNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_not_eligible")]
        #pragma warning disable CS1591
        UserNotEligible,
        #pragma warning restore CS1591
        [EnumMember(Value = "group_not_found")]
        #pragma warning disable CS1591
        GroupNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "app_not_found")]
        #pragma warning disable CS1591
        AppNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "app_has_non_draft_versions")]
        #pragma warning disable CS1591
        AppHasNonDraftVersions,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid_status_transition")]
        #pragma warning disable CS1591
        InvalidStatusTransition,
        #pragma warning restore CS1591
        [EnumMember(Value = "translation_validation_failed")]
        #pragma warning disable CS1591
        TranslationValidationFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "content_not_found")]
        #pragma warning disable CS1591
        ContentNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "doctype_not_found")]
        #pragma warning disable CS1591
        DoctypeNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "design_not_found")]
        #pragma warning disable CS1591
        DesignNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "offset_too_large")]
        #pragma warning disable CS1591
        OffsetTooLarge,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_not_found")]
        #pragma warning disable CS1591
        PageNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "design_or_comment_not_found")]
        #pragma warning disable CS1591
        DesignOrCommentNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "design_or_thread_not_found")]
        #pragma warning disable CS1591
        DesignOrThreadNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "review_dismissed")]
        #pragma warning disable CS1591
        ReviewDismissed,
        #pragma warning restore CS1591
        [EnumMember(Value = "design_type_not_found")]
        #pragma warning disable CS1591
        DesignTypeNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "team_not_found")]
        #pragma warning disable CS1591
        TeamNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "team_is_default")]
        #pragma warning disable CS1591
        TeamIsDefault,
        #pragma warning restore CS1591
        [EnumMember(Value = "comment_not_found")]
        #pragma warning disable CS1591
        CommentNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "too_many_comments")]
        #pragma warning disable CS1591
        TooManyComments,
        #pragma warning restore CS1591
        [EnumMember(Value = "too_many_replies")]
        #pragma warning disable CS1591
        TooManyReplies,
        #pragma warning restore CS1591
        [EnumMember(Value = "message_too_long")]
        #pragma warning disable CS1591
        MessageTooLong,
        #pragma warning restore CS1591
        [EnumMember(Value = "thread_not_found")]
        #pragma warning disable CS1591
        ThreadNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "reply_not_found")]
        #pragma warning disable CS1591
        ReplyNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "design_not_fillable")]
        #pragma warning disable CS1591
        DesignNotFillable,
        #pragma warning restore CS1591
        [EnumMember(Value = "autofill_data_invalid")]
        #pragma warning disable CS1591
        AutofillDataInvalid,
        #pragma warning restore CS1591
        [EnumMember(Value = "feature_not_available")]
        #pragma warning disable CS1591
        FeatureNotAvailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsupported_design_type")]
        #pragma warning disable CS1591
        UnsupportedDesignType,
        #pragma warning restore CS1591
        [EnumMember(Value = "design_generation_not_enabled")]
        #pragma warning disable CS1591
        DesignGenerationNotEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "license_required")]
        #pragma warning disable CS1591
        LicenseRequired,
        #pragma warning restore CS1591
        [EnumMember(Value = "input_unsafe")]
        #pragma warning disable CS1591
        InputUnsafe,
        #pragma warning restore CS1591
        [EnumMember(Value = "display_name_unavailable")]
        #pragma warning disable CS1591
        DisplayNameUnavailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_not_managed")]
        #pragma warning disable CS1591
        UserNotManaged,
        #pragma warning restore CS1591
        [EnumMember(Value = "saml_team_id_conflict")]
        #pragma warning disable CS1591
        SamlTeamIdConflict,
        #pragma warning restore CS1591
        [EnumMember(Value = "saml_name_id_not_available")]
        #pragma warning disable CS1591
        SamlNameIdNotAvailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_email_unverified")]
        #pragma warning disable CS1591
        UserEmailUnverified,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_not_active")]
        #pragma warning disable CS1591
        UserNotActive,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_pending_consent")]
        #pragma warning disable CS1591
        UserPendingConsent,
        #pragma warning restore CS1591
        [EnumMember(Value = "account_exists")]
        #pragma warning disable CS1591
        AccountExists,
        #pragma warning restore CS1591
    }
}
