// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FolderItemType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "design")]
        #pragma warning disable CS1591
        Design,
        #pragma warning restore CS1591
        [EnumMember(Value = "folder")]
        #pragma warning disable CS1591
        Folder,
        #pragma warning restore CS1591
        [EnumMember(Value = "image")]
        #pragma warning disable CS1591
        Image,
        #pragma warning restore CS1591
        [EnumMember(Value = "brand_template")]
        #pragma warning disable CS1591
        BrandTemplate,
        #pragma warning restore CS1591
    }
}
