// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Aggregated analytics metrics for a design.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetDesignAnalyticsResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The average view duration in seconds.</summary>
        public long? AverageViewDurationSeconds { get; set; }
        /// <summary>The total number of views.</summary>
        public long? TotalViewCount { get; set; }
        /// <summary>The total view duration in seconds.</summary>
        public long? TotalViewDurationSeconds { get; set; }
        /// <summary>The number of unique viewers.</summary>
        public long? UniqueViewCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.GetDesignAnalyticsResponse"/> and sets the default values.
        /// </summary>
        public GetDesignAnalyticsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.GetDesignAnalyticsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.GetDesignAnalyticsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.GetDesignAnalyticsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "average_view_duration_seconds", n => { AverageViewDurationSeconds = n.GetLongValue(); } },
                { "total_view_count", n => { TotalViewCount = n.GetLongValue(); } },
                { "total_view_duration_seconds", n => { TotalViewDurationSeconds = n.GetLongValue(); } },
                { "unique_view_count", n => { UniqueViewCount = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("average_view_duration_seconds", AverageViewDurationSeconds);
            writer.WriteLongValue("total_view_count", TotalViewCount);
            writer.WriteLongValue("total_view_duration_seconds", TotalViewDurationSeconds);
            writer.WriteLongValue("unique_view_count", UniqueViewCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
