// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Export the email design as a standalone HTML file with hosted assets.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HtmlStandaloneExportFormat : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The pages of the design to export. Currently only a single page can be exported. If not provided,the first page of the design is used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Pages { get; set; }
#nullable restore
#else
        public List<int?> Pages { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Canva.OpenApiClient.Models.HtmlStandaloneType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.HtmlStandaloneExportFormat"/> and sets the default values.
        /// </summary>
        public HtmlStandaloneExportFormat()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.HtmlStandaloneExportFormat"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.HtmlStandaloneExportFormat CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.HtmlStandaloneExportFormat();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "pages", n => { Pages = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Canva.OpenApiClient.Models.HtmlStandaloneType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<int?>("pages", Pages);
            writer.WriteEnumValue<global::Soenneker.Canva.OpenApiClient.Models.HtmlStandaloneType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
