// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>The model to use for image generation. We recommend omitting this parameter: Canvathen selects the best available model for the request and falls back to anothermodel if one is temporarily unavailable. Set it only if you need a specific model&apos;soutput. If the requested model can&apos;t serve the request, the job fails. Canva neveruses a different model to serve the request.The model strengths below are based on Canva&apos;s evaluations. Results vary byprompt, so test with your own prompts before pinning a model.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ImageGenerationModel
    {
        [EnumMember(Value = "lucid_origin")]
        #pragma warning disable CS1591
        LucidOrigin,
        #pragma warning restore CS1591
        [EnumMember(Value = "z_image_turbo")]
        #pragma warning disable CS1591
        ZImageTurbo,
        #pragma warning restore CS1591
    }
}
