// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Details about the image generation job. If the job status is `success`, the job&apos;s`result` is present.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImageGenerationJob : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If the image generation job fails, this object provides details about the error. Only present if status is `failed`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationError? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationError Error { get; set; }
#endif
        /// <summary>The image generation job ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Result of the image generation job. Only present if job status is `success`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationJobResult? Result { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationJobResult Result { get; set; }
#endif
        /// <summary>The status of the image generation job. A newly created job will be `in_progress` andwill eventually become `success` or `failed`. If the status is `success`, the job&apos;s`result` is present.</summary>
        public global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationJobStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationJob"/> and sets the default values.
        /// </summary>
        public ImageGenerationJob()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationJob"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationJob CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationJob();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationError>(global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationError.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "result", n => { Result = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationJobResult>(global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationJobResult.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationJobStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationError>("error", Error);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationJobResult>("result", Result);
            writer.WriteEnumValue<global::Soenneker.Canva.OpenApiClient.Models.ImageGenerationJobStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
