// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>A short string about why the import failed. This field can be used to handle errorsprogrammatically.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ImageToDesignImportErrorCode
    {
        [EnumMember(Value = "bad_input")]
        #pragma warning disable CS1591
        BadInput,
        #pragma warning restore CS1591
        [EnumMember(Value = "moderation_error")]
        #pragma warning disable CS1591
        ModerationError,
        #pragma warning restore CS1591
        [EnumMember(Value = "quota_exceeded")]
        #pragma warning disable CS1591
        QuotaExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "design_creation_throttled")]
        #pragma warning disable CS1591
        DesignCreationThrottled,
        #pragma warning restore CS1591
        [EnumMember(Value = "internal_error")]
        #pragma warning disable CS1591
        InternalError,
        #pragma warning restore CS1591
    }
}
