// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>Error code indicating what went wrong with the image transformation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ImageTransformationErrorCode
    {
        [EnumMember(Value = "no_foreground_found")]
        #pragma warning disable CS1591
        NoForegroundFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "quota_exceeded")]
        #pragma warning disable CS1591
        QuotaExceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "internal_error")]
        #pragma warning disable CS1591
        InternalError,
        #pragma warning restore CS1591
    }
}
