// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Inserts pages from a source design into the target design.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InsertPagesDesignMergeOperation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Insert after this one-based page number in the evolving target layout. Use 0 to insert at the beginning, and the default is inserting at the end (append).</summary>
        public int? AfterPageNumber { get; set; }
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.MergeSourceForInsertPagesOperation? Source { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.MergeSourceForInsertPagesOperation Source { get; set; }
#endif
        /// <summary>The type of merge operation.</summary>
        public global::Soenneker.Canva.OpenApiClient.Models.InsertPagesType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.InsertPagesDesignMergeOperation"/> and sets the default values.
        /// </summary>
        public InsertPagesDesignMergeOperation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.InsertPagesDesignMergeOperation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.InsertPagesDesignMergeOperation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.InsertPagesDesignMergeOperation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "after_page_number", n => { AfterPageNumber = n.GetIntValue(); } },
                { "source", n => { Source = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.MergeSourceForInsertPagesOperation>(global::Soenneker.Canva.OpenApiClient.Models.MergeSourceForInsertPagesOperation.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Canva.OpenApiClient.Models.InsertPagesType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("after_page_number", AfterPageNumber);
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.MergeSourceForInsertPagesOperation>("source", Source);
            writer.WriteEnumValue<global::Soenneker.Canva.OpenApiClient.Models.InsertPagesType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
