// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>The orientation and resolution of the exported video. Orientation is either `horizontal` or`vertical`, and resolution is one of `480p`, `720p`, `1080p` or `4k`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Mp4ExportQuality
    {
        [EnumMember(Value = "horizontal_480p")]
        #pragma warning disable CS1591
        Horizontal480P,
        #pragma warning restore CS1591
        [EnumMember(Value = "horizontal_720p")]
        #pragma warning disable CS1591
        Horizontal720P,
        #pragma warning restore CS1591
        [EnumMember(Value = "horizontal_1080p")]
        #pragma warning disable CS1591
        Horizontal1080P,
        #pragma warning restore CS1591
        [EnumMember(Value = "horizontal_4k")]
        #pragma warning disable CS1591
        Horizontal4K,
        #pragma warning restore CS1591
        [EnumMember(Value = "vertical_480p")]
        #pragma warning disable CS1591
        Vertical480P,
        #pragma warning restore CS1591
        [EnumMember(Value = "vertical_720p")]
        #pragma warning disable CS1591
        Vertical720P,
        #pragma warning restore CS1591
        [EnumMember(Value = "vertical_1080p")]
        #pragma warning disable CS1591
        Vertical1080P,
        #pragma warning restore CS1591
        [EnumMember(Value = "vertical_4k")]
        #pragma warning disable CS1591
        Vertical4K,
        #pragma warning restore CS1591
    }
}
