// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>The resolution of the exported video, as a target number of pixels. The resolution is one of`480p`, `720p`, `1080p` or `4k`.The exported video always has the same aspect ratio as the design, which matches creating adownload from the Canva editor. The resolution sets how many pixels to target, and thedesign&apos;s aspect ratio decides how they&apos;re split between width and height, so the`horizontal` and `vertical` values of a given resolution produce the same output:- A 2160x3840 portrait design exported as `horizontal_4k` is 2160x3840, not 3840x2160. The  orientation in the value&apos;s name doesn&apos;t rotate or crop the design.- A 1000x2000 design exported as `horizontal_720p` is 678x1357, the 1:2 size closest to the  921,600 pixels of 1280x720. Aspect ratios that don&apos;t match a standard video size aren&apos;t  rounded to one.- A square design exported as `horizontal_4k` or `vertical_4k` is 2880x2880, the square with  the same number of pixels as 3840x2160.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Mp4ExportQuality
    {
        [EnumMember(Value = "horizontal_480p")]
        #pragma warning disable CS1591
        Horizontal480P,
        #pragma warning restore CS1591
        [EnumMember(Value = "horizontal_720p")]
        #pragma warning disable CS1591
        Horizontal720P,
        #pragma warning restore CS1591
        [EnumMember(Value = "horizontal_1080p")]
        #pragma warning disable CS1591
        Horizontal1080P,
        #pragma warning restore CS1591
        [EnumMember(Value = "horizontal_4k")]
        #pragma warning disable CS1591
        Horizontal4K,
        #pragma warning restore CS1591
        [EnumMember(Value = "vertical_480p")]
        #pragma warning disable CS1591
        Vertical480P,
        #pragma warning restore CS1591
        [EnumMember(Value = "vertical_720p")]
        #pragma warning disable CS1591
        Vertical720P,
        #pragma warning restore CS1591
        [EnumMember(Value = "vertical_1080p")]
        #pragma warning disable CS1591
        Vertical1080P,
        #pragma warning restore CS1591
        [EnumMember(Value = "vertical_4k")]
        #pragma warning disable CS1591
        Vertical4K,
        #pragma warning restore CS1591
    }
}
