// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// View duration metrics for a single page.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PageViewDuration : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The average time spent viewing this page, in seconds. This is omitted for `by_viewer` filters.</summary>
        public double? AverageDurationSeconds { get; set; }
        /// <summary>The page ID. This is omitted for design types that do not support page IDs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PageId { get; set; }
#nullable restore
#else
        public string PageId { get; set; }
#endif
        /// <summary>The total time spent viewing this page, in seconds.</summary>
        public long? TotalViewDurationSeconds { get; set; }
        /// <summary>The number of unique viewers for this page. This is omitted for `by_viewer` filters.</summary>
        public long? UniqueViewCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.PageViewDuration"/> and sets the default values.
        /// </summary>
        public PageViewDuration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.PageViewDuration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.PageViewDuration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.PageViewDuration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "average_duration_seconds", n => { AverageDurationSeconds = n.GetDoubleValue(); } },
                { "page_id", n => { PageId = n.GetStringValue(); } },
                { "total_view_duration_seconds", n => { TotalViewDurationSeconds = n.GetLongValue(); } },
                { "unique_view_count", n => { UniqueViewCount = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("average_duration_seconds", AverageDurationSeconds);
            writer.WriteStringValue("page_id", PageId);
            writer.WriteLongValue("total_view_duration_seconds", TotalViewDurationSeconds);
            writer.WriteLongValue("unique_view_count", UniqueViewCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
