// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Export the design as a PNG. Height or width (or both) may be specified, otherwisethe file will be exported at it&apos;s default size. You may also specify whether to export thefile losslessly, and whether to export a multi-page design as a single image.If the user is on the Canva Free plan, the export height and width for a fixed-dimension design can&apos;t be upscaled by more than a factor of `1.125`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PngExportFormat : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When `true`, multi-page designs are merged into a single image.When `false` (default), each page is exported as a separate image.</summary>
        public bool? AsSingleImage { get; set; }
        /// <summary>Specifies the export quality of the design.</summary>
        public global::Soenneker.Canva.OpenApiClient.Models.ExportQuality? ExportQuality { get; set; }
        /// <summary>Specify the height in pixels of the exported image. Note the following behavior:- If no height or width is specified, the image is exported using the dimensions of the design.- If only one of height or width is specified, then the image is scaled to match that dimension, respecting the design&apos;s aspect ratio.- If both the height and width are specified, but the values don&apos;t match the design&apos;s aspect ratio, the export defaults to the larger dimension.</summary>
        public int? Height { get; set; }
        /// <summary>If set to `true` (default), the PNG is exported without compression.If set to `false`, the PNG is compressed using a lossy compression algorithm.AVAILABILITY: Lossy PNG compression is only available to users on a Canva plan that has premium features, such as Canva Pro. If the user is on the Canva Free plan and this parameter is set to `false`, the export operation will fail.</summary>
        public bool? Lossless { get; set; }
        /// <summary>To specify which pages to export in a multi-page design, provide the page numbers asan array. The first page in a design is page `1`.If `pages` isn&apos;t specified, all the pages are exported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Pages { get; set; }
#nullable restore
#else
        public List<int?> Pages { get; set; }
#endif
        /// <summary>If set to `true`, the PNG is exported with a transparent background.AVAILABILITY: This option is only available to users on a Canva plan that has premium features, such as Canva Pro. If the user is on the Canva Free plan and this parameter is set to `true`, the export operation will fail.</summary>
        public bool? TransparentBackground { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.Canva.OpenApiClient.Models.PngType? Type { get; set; }
        /// <summary>Specify the width in pixels of the exported image. Note the following behavior:- If no width or height is specified, the image is exported using the dimensions of the design.- If only one of width or height is specified, then the image is scaled to match that dimension, respecting the design&apos;s aspect ratio.- If both the width and height are specified, but the values don&apos;t match the design&apos;s aspect ratio, the export defaults to the larger dimension.</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.PngExportFormat"/> and sets the default values.
        /// </summary>
        public PngExportFormat()
        {
            AdditionalData = new Dictionary<string, object>();
            AsSingleImage = false;
            Lossless = true;
            TransparentBackground = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.PngExportFormat"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.PngExportFormat CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.PngExportFormat();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "as_single_image", n => { AsSingleImage = n.GetBoolValue(); } },
                { "export_quality", n => { ExportQuality = n.GetEnumValue<global::Soenneker.Canva.OpenApiClient.Models.ExportQuality>(); } },
                { "height", n => { Height = n.GetIntValue(); } },
                { "lossless", n => { Lossless = n.GetBoolValue(); } },
                { "pages", n => { Pages = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "transparent_background", n => { TransparentBackground = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Canva.OpenApiClient.Models.PngType>(); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("as_single_image", AsSingleImage);
            writer.WriteEnumValue<global::Soenneker.Canva.OpenApiClient.Models.ExportQuality>("export_quality", ExportQuality);
            writer.WriteIntValue("height", Height);
            writer.WriteBoolValue("lossless", Lossless);
            writer.WriteCollectionOfPrimitiveValues<int?>("pages", Pages);
            writer.WriteBoolValue("transparent_background", TransparentBackground);
            writer.WriteEnumValue<global::Soenneker.Canva.OpenApiClient.Models.PngType>("type", Type);
            writer.WriteIntValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
