// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>The name of the design type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PresetDesignTypeName
    {
        [EnumMember(Value = "doc")]
        #pragma warning disable CS1591
        Doc,
        #pragma warning restore CS1591
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "presentation")]
        #pragma warning disable CS1591
        Presentation,
        #pragma warning restore CS1591
        [EnumMember(Value = "whiteboard")]
        #pragma warning disable CS1591
        Whiteboard,
        #pragma warning restore CS1591
    }
}
