// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>For generating an access token using a refresh token.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RefreshTokenGrantType
    {
        [EnumMember(Value = "refresh_token")]
        #pragma warning disable CS1591
        RefreshToken,
        #pragma warning restore CS1591
    }
}
