// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Data about the reply comment, including the message, author, andthe object (such as a design) the comment is attached to.
    /// </summary>
    [Obsolete("")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReplyComment : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Identifying information about the object (such as a design) that the comment is attached to.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.CommentObject? AttachedTo { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.CommentObject AttachedTo { get; set; }
#endif
        /// <summary>Metadata for the user, consisting of the User ID and display name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.User? Author { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.User Author { get; set; }
#endif
        /// <summary>When the comment or reply was created, as a Unix timestamp(in seconds since the Unix Epoch).</summary>
        public long? CreatedAt { get; set; }
        /// <summary>The ID of the comment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The Canva users mentioned in the comment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.ReplyCommentMentionsProperty? Mentions { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.ReplyCommentMentionsProperty Mentions { get; set; }
#endif
        /// <summary>The comment message. This is the comment body shown in the Canva UI.User mentions are shown here in the format `[user_id:team_id]`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The ID of the comment thread this reply is in. This ID is the same as the `id` of theparent comment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThreadId { get; set; }
#nullable restore
#else
        public string ThreadId { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Canva.OpenApiClient.Models.ReplyType? Type { get; set; }
        /// <summary>When the comment or reply was last updated, as a Unix timestamp(in seconds since the Unix Epoch).</summary>
        public long? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.ReplyComment"/> and sets the default values.
        /// </summary>
        public ReplyComment()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.ReplyComment"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.ReplyComment CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.ReplyComment();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attached_to", n => { AttachedTo = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.CommentObject>(global::Soenneker.Canva.OpenApiClient.Models.CommentObject.CreateFromDiscriminatorValue); } },
                { "author", n => { Author = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.User>(global::Soenneker.Canva.OpenApiClient.Models.User.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetLongValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "mentions", n => { Mentions = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.ReplyCommentMentionsProperty>(global::Soenneker.Canva.OpenApiClient.Models.ReplyCommentMentionsProperty.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "thread_id", n => { ThreadId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Canva.OpenApiClient.Models.ReplyType>(); } },
                { "updated_at", n => { UpdatedAt = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.CommentObject>("attached_to", AttachedTo);
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.User>("author", Author);
            writer.WriteLongValue("created_at", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.ReplyCommentMentionsProperty>("mentions", Mentions);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("thread_id", ThreadId);
            writer.WriteEnumValue<global::Soenneker.Canva.OpenApiClient.Models.ReplyType>("type", Type);
            writer.WriteLongValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
