// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// A reply to a thread.The `author` of the reply might be missing if that user account no longer exists.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Reply : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Metadata for the user, consisting of the User ID and display name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.User? Author { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.User Author { get; set; }
#endif
        /// <summary>The content of a comment thread or reply.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.CommentContent? Content { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.CommentContent Content { get; set; }
#endif
        /// <summary>When the reply was created, as a Unix timestamp(in seconds since the Unix Epoch).</summary>
        public long? CreatedAt { get; set; }
        /// <summary>The ID of the design that the thread for this reply is attached to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DesignId { get; set; }
#nullable restore
#else
        public string DesignId { get; set; }
#endif
        /// <summary>The ID of the reply.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The Canva users mentioned in the comment thread or reply.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.ReplyMentionsProperty? Mentions { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.ReplyMentionsProperty Mentions { get; set; }
#endif
        /// <summary>The ID of the thread this reply is in.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThreadId { get; set; }
#nullable restore
#else
        public string ThreadId { get; set; }
#endif
        /// <summary>When the reply was last updated, as a Unix timestamp(in seconds since the Unix Epoch).</summary>
        public long? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.Reply"/> and sets the default values.
        /// </summary>
        public Reply()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.Reply"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.Reply CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.Reply();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "author", n => { Author = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.User>(global::Soenneker.Canva.OpenApiClient.Models.User.CreateFromDiscriminatorValue); } },
                { "content", n => { Content = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.CommentContent>(global::Soenneker.Canva.OpenApiClient.Models.CommentContent.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetLongValue(); } },
                { "design_id", n => { DesignId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "mentions", n => { Mentions = n.GetObjectValue<global::Soenneker.Canva.OpenApiClient.Models.ReplyMentionsProperty>(global::Soenneker.Canva.OpenApiClient.Models.ReplyMentionsProperty.CreateFromDiscriminatorValue); } },
                { "thread_id", n => { ThreadId = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.User>("author", Author);
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.CommentContent>("content", Content);
            writer.WriteLongValue("created_at", CreatedAt);
            writer.WriteStringValue("design_id", DesignId);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.ReplyMentionsProperty>("mentions", Mentions);
            writer.WriteStringValue("thread_id", ThreadId);
            writer.WriteLongValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
