// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// A suggestion thread.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SuggestionThreadType : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The current status of the suggestion.</summary>
        public global::Soenneker.Canva.OpenApiClient.Models.SuggestionStatus? Status { get; set; }
        /// <summary>The suggested_edits property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Canva.OpenApiClient.Models.SuggestedEdit>? SuggestedEdits { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Canva.OpenApiClient.Models.SuggestedEdit> SuggestedEdits { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Canva.OpenApiClient.Models.SuggestionType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.Models.SuggestionThreadType"/> and sets the default values.
        /// </summary>
        public SuggestionThreadType()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.SuggestionThreadType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.SuggestionThreadType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Canva.OpenApiClient.Models.SuggestionThreadType();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Canva.OpenApiClient.Models.SuggestionStatus>(); } },
                { "suggested_edits", n => { SuggestedEdits = n.GetCollectionOfObjectValues<global::Soenneker.Canva.OpenApiClient.Models.SuggestedEdit>(global::Soenneker.Canva.OpenApiClient.Models.SuggestedEdit.CreateFromDiscriminatorValue)?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Canva.OpenApiClient.Models.SuggestionType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Canva.OpenApiClient.Models.SuggestionStatus>("status", Status);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Canva.OpenApiClient.Models.SuggestedEdit>("suggested_edits", SuggestedEdits);
            writer.WriteEnumValue<global::Soenneker.Canva.OpenApiClient.Models.SuggestionType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
