// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Canva.OpenApiClient.Models.CommentThreadType"/>, <see cref="global::Soenneker.Canva.OpenApiClient.Models.SuggestionThreadType"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ThreadType : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.CommentThreadType"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.CommentThreadType? CommentThreadType { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.CommentThreadType CommentThreadType { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Canva.OpenApiClient.Models.SuggestionThreadType"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Canva.OpenApiClient.Models.SuggestionThreadType? SuggestionThreadType { get; set; }
#nullable restore
#else
        public global::Soenneker.Canva.OpenApiClient.Models.SuggestionThreadType SuggestionThreadType { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.ThreadType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Canva.OpenApiClient.Models.ThreadType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Canva.OpenApiClient.Models.ThreadType();
            if("comment".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CommentThreadType = new global::Soenneker.Canva.OpenApiClient.Models.CommentThreadType();
            }
            else if("suggestion".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SuggestionThreadType = new global::Soenneker.Canva.OpenApiClient.Models.SuggestionThreadType();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CommentThreadType != null)
            {
                return CommentThreadType.GetFieldDeserializers();
            }
            else if(SuggestionThreadType != null)
            {
                return SuggestionThreadType.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CommentThreadType != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.CommentThreadType>(null, CommentThreadType);
            }
            else if(SuggestionThreadType != null)
            {
                writer.WriteObjectValue<global::Soenneker.Canva.OpenApiClient.Models.SuggestionThreadType>(null, SuggestionThreadType);
            }
        }
    }
}
#pragma warning restore CS0618
