// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Canva.OpenApiClient.Models
{
    /// <summary>For backward compatibility, if `type` isn&apos;t specified in the request, the request type will be assumed to be `type_and_asset`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TypeAndAssetType
    {
        [EnumMember(Value = "type_and_asset")]
        #pragma warning disable CS1591
        TypeAndAsset,
        #pragma warning restore CS1591
    }
}
