// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Canva.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Canva.OpenApiClient.V1.Folders.Item.Items
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\folders\{folderId}\items
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ItemsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.V1.Folders.Item.Items.ItemsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ItemsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/folders/{folderId}/items{?continuation*,item_types,limit*,pin_status*,sort_by*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.V1.Folders.Item.Items.ItemsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ItemsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/folders/{folderId}/items{?continuation*,item_types,limit*,pin_status*,sort_by*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists the items in a folder, including each item&apos;s `type`.Folders can contain:- Other folders.- Designs, such as Instagram posts, Presentations, and Documents ([Canva Docs](https://www.canva.com/create/documents/)).- Image assets.- Brand templates. To include `brand_template` items in the response, you must explicitly specify it in the `item_types` parameter.  AVAILABILITY: Brand template items are only returned for users on a Canva plan with access to brand templates (such as Canva Pro, Canva Teams, or Canva Enterprise). For more information, see [Brand templates](https://www.canva.dev/docs/connect/api-reference/brand-templates/).Currently, video assets are not returned in the response.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.ListFolderItemsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Canva.OpenApiClient.Models.ListFolderItemsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Canva.OpenApiClient.V1.Folders.Item.Items.ItemsRequestBuilder.ItemsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Canva.OpenApiClient.Models.ListFolderItemsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Canva.OpenApiClient.V1.Folders.Item.Items.ItemsRequestBuilder.ItemsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Canva.OpenApiClient.Models.ListFolderItemsResponse>(requestInfo, global::Soenneker.Canva.OpenApiClient.Models.ListFolderItemsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists the items in a folder, including each item&apos;s `type`.Folders can contain:- Other folders.- Designs, such as Instagram posts, Presentations, and Documents ([Canva Docs](https://www.canva.com/create/documents/)).- Image assets.- Brand templates. To include `brand_template` items in the response, you must explicitly specify it in the `item_types` parameter.  AVAILABILITY: Brand template items are only returned for users on a Canva plan with access to brand templates (such as Canva Pro, Canva Teams, or Canva Enterprise). For more information, see [Brand templates](https://www.canva.dev/docs/connect/api-reference/brand-templates/).Currently, video assets are not returned in the response.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Canva.OpenApiClient.V1.Folders.Item.Items.ItemsRequestBuilder.ItemsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Canva.OpenApiClient.V1.Folders.Item.Items.ItemsRequestBuilder.ItemsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.V1.Folders.Item.Items.ItemsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Canva.OpenApiClient.V1.Folders.Item.Items.ItemsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Canva.OpenApiClient.V1.Folders.Item.Items.ItemsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists the items in a folder, including each item&apos;s `type`.Folders can contain:- Other folders.- Designs, such as Instagram posts, Presentations, and Documents ([Canva Docs](https://www.canva.com/create/documents/)).- Image assets.- Brand templates. To include `brand_template` items in the response, you must explicitly specify it in the `item_types` parameter.  AVAILABILITY: Brand template items are only returned for users on a Canva plan with access to brand templates (such as Canva Pro, Canva Teams, or Canva Enterprise). For more information, see [Brand templates](https://www.canva.dev/docs/connect/api-reference/brand-templates/).Currently, video assets are not returned in the response.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ItemsRequestBuilderGetQueryParameters 
        {
            /// <summary>If the success response contains a continuation token, the folder contains more itemsyou can list. You can use this token as a query parameter and retrieve moreitems from the list, for example`/v1/folders/{folderId}/items?continuation={continuation}`.To retrieve all the items in a folder, you might need to make multiple requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("continuation")]
            public string? Continuation { get; set; }
#nullable restore
#else
            [QueryParameter("continuation")]
            public string Continuation { get; set; }
#endif
            /// <summary>Filter the folder items to only return specified types. The available types are:`design`, `folder`, `image`, and `brand_template`. To filter for more than one item type,provide a comma-delimited list.If not specified, defaults to returning `design`, `folder`, and `image` items.To include `brand_template` items, you must explicitly specify it in this parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("item_types")]
            public global::Soenneker.Canva.OpenApiClient.Models.FolderItemType[]? ItemTypes { get; set; }
#nullable restore
#else
            [QueryParameter("item_types")]
            public global::Soenneker.Canva.OpenApiClient.Models.FolderItemType[] ItemTypes { get; set; }
#endif
            #pragma warning disable CS1591
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            #pragma warning restore CS1591
            /// <summary>Filter the folder items by their pinned status.</summary>
            [QueryParameter("pin_status")]
            public global::Soenneker.Canva.OpenApiClient.Models.FolderItemPinStatus? PinStatus { get; set; }
            /// <summary>Sort the list of folder items.</summary>
            [QueryParameter("sort_by")]
            public global::Soenneker.Canva.OpenApiClient.Models.FolderItemSortBy? SortBy { get; set; }
        }
    }
}
#pragma warning restore CS0618
