// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Canva.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Canva.OpenApiClient.V1.Designs.Item.Comments.Item.Replies.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\designs\{designId}\comments\{threadId}\replies\{replyId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithReplyItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.V1.Designs.Item.Comments.Item.Replies.Item.WithReplyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithReplyItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/designs/{designId}/comments/{threadId}/replies/{replyId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.V1.Designs.Item.Comments.Item.Replies.Item.WithReplyItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithReplyItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/designs/{designId}/comments/{threadId}/replies/{replyId}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;Warning&gt;This API is currently provided as a preview. Be aware of the following:- There might be unannounced breaking changes.- Any breaking changes to preview APIs won&apos;t produce a new [API version](https://www.canva.dev/docs/connect/versions/).- Public integrations that use preview APIs will not pass the review process, and can&apos;t be made available to all Canva users.&lt;/Warning&gt;Gets a reply to a comment or suggestion thread on a design.For information on comments and how they&apos;re used in the Canva UI, see the[Canva Help Center](https://www.canva.com/help/comments/).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.Models.GetReplyResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Canva.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Canva.OpenApiClient.Models.GetReplyResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Canva.OpenApiClient.Models.GetReplyResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "403", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Canva.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Canva.OpenApiClient.Models.GetReplyResponse>(requestInfo, global::Soenneker.Canva.OpenApiClient.Models.GetReplyResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;Warning&gt;This API is currently provided as a preview. Be aware of the following:- There might be unannounced breaking changes.- Any breaking changes to preview APIs won&apos;t produce a new [API version](https://www.canva.dev/docs/connect/versions/).- Public integrations that use preview APIs will not pass the review process, and can&apos;t be made available to all Canva users.&lt;/Warning&gt;Gets a reply to a comment or suggestion thread on a design.For information on comments and how they&apos;re used in the Canva UI, see the[Canva Help Center](https://www.canva.com/help/comments/).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Canva.OpenApiClient.V1.Designs.Item.Comments.Item.Replies.Item.WithReplyItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Canva.OpenApiClient.V1.Designs.Item.Comments.Item.Replies.Item.WithReplyItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Canva.OpenApiClient.V1.Designs.Item.Comments.Item.Replies.Item.WithReplyItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
