// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Canva.OpenApiClient.V1.PrintPartner.Designs;
using Soenneker.Canva.OpenApiClient.V1.PrintPartner.Exports;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Canva.OpenApiClient.V1.PrintPartner
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\print-partner
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PrintPartnerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The designs property</summary>
        public global::Soenneker.Canva.OpenApiClient.V1.PrintPartner.Designs.DesignsRequestBuilder Designs
        {
            get => new global::Soenneker.Canva.OpenApiClient.V1.PrintPartner.Designs.DesignsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exports property</summary>
        public global::Soenneker.Canva.OpenApiClient.V1.PrintPartner.Exports.ExportsRequestBuilder Exports
        {
            get => new global::Soenneker.Canva.OpenApiClient.V1.PrintPartner.Exports.ExportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.V1.PrintPartner.PrintPartnerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PrintPartnerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/print-partner", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Canva.OpenApiClient.V1.PrintPartner.PrintPartnerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PrintPartnerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/print-partner", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
